#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,2,4,9,19,41,43,54&i=1,2,3,4,15,16,17,28,29,30&v=4,5,-1,255,27,26,25,36,34,39 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ILI9341, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define L10N_LANGUAGE      RU
#define DSP_MODEL      DSP_ILI9341
#define ENC_BTNR      36
#define ENC_BTNL      34
#define ENC_BTNB      39
#define ENC_INTERNALPULLUP      false


#endif